version: "3.7"

services:
  frontend:
    image: node:latest
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: npm run dev
    networks:
      - mynet

  backend:
    image: node:latest
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app/backend
    command: npm run dev
    networks:
      - mynet

networks:
  mynet:
