services:
  frontend:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: npm run dev
    networks:
      - mynet

  backend:
    image: node:latest
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    working_dir: /app/backend
    command: npm run dev
    networks:
      - mynet

  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: a1s2d3f4
    ports: 
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql
    networks:
      - mynet

networks:
  mynet:
